//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Symber.Web.Properties
{


	/// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Symber.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 File &apos;{0}&apos; not found. 的本地化字符串。
        /// </summary>
        internal static string AP_FileNotFound {
            get {
                return ResourceManager.GetString("AP_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index {0} is out of range. 的本地化字符串。
        /// </summary>
        internal static string AP_IndexOutOfRange {
            get {
                return ResourceManager.GetString("AP_IndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assignment. 的本地化字符串。
        /// </summary>
        internal static string APBusiness_AssignmentComment {
            get {
                return ResourceManager.GetString("APBusiness_AssignmentComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch Delete Data. 的本地化字符串。
        /// </summary>
        internal static string APBusiness_BatchDeleteComment {
            get {
                return ResourceManager.GetString("APBusiness_BatchDeleteComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch Insert Data. 的本地化字符串。
        /// </summary>
        internal static string APBusiness_BatchInsertComment {
            get {
                return ResourceManager.GetString("APBusiness_BatchInsertComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch Update Data. 的本地化字符串。
        /// </summary>
        internal static string APBusiness_BatchUpdateComment {
            get {
                return ResourceManager.GetString("APBusiness_BatchUpdateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 APBplDef is a Partial class auto-generated by tool. It is used to define every Bpl classes. You can add Partial classes of the same name to extend. 的本地化字符串。
        /// </summary>
        internal static string APBusiness_BplDefComment {
            get {
                return ResourceManager.GetString("APBusiness_BplDefComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add data to cache. 的本地化字符串。
        /// </summary>
        internal static string APBusiness_CacheAddComment {
            get {
                return ResourceManager.GetString("APBusiness_CacheAddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear cache. 的本地化字符串。
        /// </summary>
        internal static string APBusiness_CacheClearComment {
            get {
                return ResourceManager.GetString("APBusiness_CacheClearComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove data from cache. 的本地化字符串。
        /// </summary>
        internal static string APBusiness_CacheRemoveComment {
            get {
                return ResourceManager.GetString("APBusiness_CacheRemoveComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cascade Delete Warning. The rule be related by &apos;{0}&apos;, can not be delete! 的本地化字符串。
        /// </summary>
        internal static string APBusiness_CascadeWarningMessage {
            get {
                return ResourceManager.GetString("APBusiness_CascadeWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check repeat data with specified column. 的本地化字符串。
        /// </summary>
        internal static string APBusiness_CheckRepeatComment {
            get {
                return ResourceManager.GetString("APBusiness_CheckRepeatComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compare equals. 的本地化字符串。
        /// </summary>
        internal static string APBusiness_CompareEqualsComment {
            get {
                return ResourceManager.GetString("APBusiness_CompareEqualsComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete data by condition. 的本地化字符串。
        /// </summary>
        internal static string APBusiness_ConditionDeleteComment {
            get {
                return ResourceManager.GetString("APBusiness_ConditionDeleteComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query by condition. 的本地化字符串。
        /// </summary>
        internal static string APBusiness_ConditionQueryComment {
            get {
                return ResourceManager.GetString("APBusiness_ConditionQueryComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query count by condition. 的本地化字符串。
        /// </summary>
        internal static string APBusiness_ConditionQueryCountComment {
            get {
                return ResourceManager.GetString("APBusiness_ConditionQueryCountComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 APDalDef is a Partial class auto-generated by tool. It is used to define every Dal classes inherit form APDal. You can add Partial classes of the same name to extend. 的本地化字符串。
        /// </summary>
        internal static string APBusiness_DalDefComment {
            get {
                return ResourceManager.GetString("APBusiness_DalDefComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 APDBDef is a Partial class auto-generated by tool. It is used to define APTableDef and APRelationDef. You can add Partial classes of the same name to extend. 的本地化字符串。
        /// </summary>
        internal static string APBusiness_DBDefComment {
            get {
                return ResourceManager.GetString("APBusiness_DBDefComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Static constractor. 的本地化字符串。
        /// </summary>
        internal static string APBusiness_DBDefStaticConstructor {
            get {
                return ResourceManager.GetString("APBusiness_DBDefStaticConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default constructor. 的本地化字符串。
        /// </summary>
        internal static string APBusiness_DefaultConstructorComment {
            get {
                return ResourceManager.GetString("APBusiness_DefaultConstructorComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete by {0}. 的本地化字符串。
        /// </summary>
        internal static string APBusiness_DeleteByComment {
            get {
                return ResourceManager.GetString("APBusiness_DeleteByComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicated value existed in column &apos;{0}&apos; of table &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string APBusiness_DuplicatedColumn {
            get {
                return ResourceManager.GetString("APBusiness_DuplicatedColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get all data. 的本地化字符串。
        /// </summary>
        internal static string APBusiness_GetAllComment {
            get {
                return ResourceManager.GetString("APBusiness_GetAllComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get the initial data of the table. 的本地化字符串。
        /// </summary>
        internal static string APBusiness_GetInitDataComment {
            get {
                return ResourceManager.GetString("APBusiness_GetInitDataComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initialize data. 的本地化字符串。
        /// </summary>
        internal static string APBusiness_InitDataComment {
            get {
                return ResourceManager.GetString("APBusiness_InitDataComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Constructor with all field values. 的本地化字符串。
        /// </summary>
        internal static string APBusiness_InitFieldsConstructorComment {
            get {
                return ResourceManager.GetString("APBusiness_InitFieldsConstructorComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Data. 的本地化字符串。
        /// </summary>
        internal static string APBusiness_InsertComment {
            get {
                return ResourceManager.GetString("APBusiness_InsertComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill the data. 的本地化字符串。
        /// </summary>
        internal static string APBusiness_MapComment {
            get {
                return ResourceManager.GetString("APBusiness_MapComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill the data delegate. 的本地化字符串。
        /// </summary>
        internal static string APBusiness_MapHandlerComment {
            get {
                return ResourceManager.GetString("APBusiness_MapHandlerComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete data by primary key. 的本地化字符串。
        /// </summary>
        internal static string APBusiness_PrimaryDeleteComment {
            get {
                return ResourceManager.GetString("APBusiness_PrimaryDeleteComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get data by PK. 的本地化字符串。
        /// </summary>
        internal static string APBusiness_PrimaryGetComment {
            get {
                return ResourceManager.GetString("APBusiness_PrimaryGetComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query by {0}. 的本地化字符串。
        /// </summary>
        internal static string APBusiness_QueryByComment {
            get {
                return ResourceManager.GetString("APBusiness_QueryByComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query count by {0}. 的本地化字符串。
        /// </summary>
        internal static string APBusiness_QueryCountByComment {
            get {
                return ResourceManager.GetString("APBusiness_QueryCountByComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target of Relation &apos;{0}&apos; missing. (masterTable, masterColumn, slaveTable, slaveColumn). 的本地化字符串。
        /// </summary>
        internal static string APBusiness_RelationTargetMissing {
            get {
                return ResourceManager.GetString("APBusiness_RelationTargetMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Data. 的本地化字符串。
        /// </summary>
        internal static string APBusiness_UpdateComment {
            get {
                return ResourceManager.GetString("APBusiness_UpdateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not Find Section &apos;{0}&apos; in config file. 的本地化字符串。
        /// </summary>
        internal static string APConfig_NotFindSection {
            get {
                return ResourceManager.GetString("APConfig_NotFindSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The parsed type &apos;{0}&apos; of the column is not supported. 的本地化字符串。
        /// </summary>
        internal static string APDal_ColumnParsedTypeNotImplemented {
            get {
                return ResourceManager.GetString("APDal_ColumnParsedTypeNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current database unsupport &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string APDal_DBUnsupport {
            get {
                return ResourceManager.GetString("APDal_DBUnsupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EnumAPColumnDef T (&apos;{0}&apos;) mast be a enum type. 的本地化字符串。
        /// </summary>
        internal static string APData_EnumAPColumnDefT {
            get {
                return ResourceManager.GetString("APData_EnumAPColumnDefT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The IAPColumnDef type of &apos;{0}&apos; unsupport parameter name. 的本地化字符串。
        /// </summary>
        internal static string APData_IAPColumnDefUnsupportParamName {
            get {
                return ResourceManager.GetString("APData_IAPColumnDefUnsupportParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The phrase type of &apos;{0}&apos; SetNext parameter type &apos;{1}&apos; error, parameter type mast be &apos;{2}&apos;. 的本地化字符串。
        /// </summary>
        internal static string APData_PhraseNextError {
            get {
                return ResourceManager.GetString("APData_PhraseNextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query data with &apos;skip&apos;, the value must be null or great then or equals 0. 的本地化字符串。
        /// </summary>
        internal static string APData_QuerySkipError {
            get {
                return ResourceManager.GetString("APData_QuerySkipError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query data with &apos;take&apos;, the value must be null or great then 0. 的本地化字符串。
        /// </summary>
        internal static string APData_QueryTakeError {
            get {
                return ResourceManager.GetString("APData_QueryTakeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query data with &apos;skip&apos;, the query must have specified primary key column. 的本地化字符串。
        /// </summary>
        internal static string APData_SkipQueryNeedPK {
            get {
                return ResourceManager.GetString("APData_SkipQueryNeedPK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command of the query is null or unknown, please check! 的本地化字符串。
        /// </summary>
        internal static string APData_UnknownQueryCommand {
            get {
                return ResourceManager.GetString("APData_UnknownQueryCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expression APColumnDef use ColumnName for alias,can not set again. 的本地化字符串。
        /// </summary>
        internal static string APDB_ExpressionColumnCannotAs {
            get {
                return ResourceManager.GetString("APDB_ExpressionColumnCannotAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expression APColumnDef can not be Sql set phrase. 的本地化字符串。
        /// </summary>
        internal static string APDB_ExpressionColumnCannotSet {
            get {
                return ResourceManager.GetString("APDB_ExpressionColumnCannotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not create APSqlConditionPhrase with &apos;Exists&apos; operator,please use APDal.Exists methods. 的本地化字符串。
        /// </summary>
        internal static string APDB_OperatorExists {
            get {
                return ResourceManager.GetString("APDB_OperatorExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The array parameter &apos;{0}&apos; should not contain duplicate values. 的本地化字符串。
        /// </summary>
        internal static string APDB_ParameterArrayDuplicateElement {
            get {
                return ResourceManager.GetString("APDB_ParameterArrayDuplicateElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The array parameter &apos;{0}&apos; should not be empty. 的本地化字符串。
        /// </summary>
        internal static string APDB_ParameterArrayEmpty {
            get {
                return ResourceManager.GetString("APDB_ParameterArrayEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The parameter &apos;{0}&apos; must not contain commas. 的本地化字符串。
        /// </summary>
        internal static string APDB_ParameterContainComma {
            get {
                return ResourceManager.GetString("APDB_ParameterContainComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The parameter &apos;{0}&apos; must not be empty. 的本地化字符串。
        /// </summary>
        internal static string APDB_ParameterEmpty {
            get {
                return ResourceManager.GetString("APDB_ParameterEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The parameter &apos;{0}&apos; is too long, it must not exceed {1} chars in length. 的本地化字符串。
        /// </summary>
        internal static string APDB_ParameterTooLong {
            get {
                return ResourceManager.GetString("APDB_ParameterTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ------------------------------------------------------------------------------
        /// This code Section was generated by Default APGen.
        /// Type is &apos;{0}&apos;, Maybe you not implementation necessary code.
        ///------------------------------------------------------------------------------ 的本地化字符串。
        /// </summary>
        internal static string APGen_DefaultGenerated {
            get {
                return ResourceManager.GetString("APGen_DefaultGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The default value for property &apos;{0}&apos; has a different type than the one of the property itself: expected {1} but was {2}. 的本地化字符串。
        /// </summary>
        internal static string APGen_DefaultValueTypeError {
            get {
                return ResourceManager.GetString("APGen_DefaultValueTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The attribute &apos;{0}&apos; may only appear once in this element. 的本地化字符串。
        /// </summary>
        internal static string APGen_DuplicateAttribute {
            get {
                return ResourceManager.GetString("APGen_DuplicateAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The element &lt;{0}&gt; may only appear once in this section. 的本地化字符串。
        /// </summary>
        internal static string APGen_DuplicateElement {
            get {
                return ResourceManager.GetString("APGen_DuplicateElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicate element in collection. 的本地化字符串。
        /// </summary>
        internal static string APGen_DuplicateElementInCollection {
            get {
                return ResourceManager.GetString("APGen_DuplicateElementInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File &apos;{0}&apos; not found. 的本地化字符串。
        /// </summary>
        internal static string APGen_FileNotFound {
            get {
                return ResourceManager.GetString("APGen_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index {0} is out of range. 的本地化字符串。
        /// </summary>
        internal static string APGen_IndexOutOfRange {
            get {
                return ResourceManager.GetString("APGen_IndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gen file does not have a valid root element. 的本地化字符串。
        /// </summary>
        internal static string APGen_InvalidRootElement {
            get {
                return ResourceManager.GetString("APGen_InvalidRootElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Required attribute &apos;{1}&apos; missing. 的本地化字符串。
        /// </summary>
        internal static string APGen_MissingRequiredAttribute {
            get {
                return ResourceManager.GetString("APGen_MissingRequiredAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property &apos;{0}&apos; is not a APGenElement. 的本地化字符串。
        /// </summary>
        internal static string APGen_NotElement {
            get {
                return ResourceManager.GetString("APGen_NotElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value of the property &apos;{0}&apos; cannot be parsed. 的本地化字符串。
        /// </summary>
        internal static string APGen_PropertyCannotBeParsed {
            get {
                return ResourceManager.GetString("APGen_PropertyCannotBeParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property &apos;{0}&apos; not found in gen element. 的本地化字符串。
        /// </summary>
        internal static string APGen_PropertyNotExist {
            get {
                return ResourceManager.GetString("APGen_PropertyNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value for the property &apos;{0}&apos; is not valid. The error is: {1}. 的本地化字符串。
        /// </summary>
        internal static string APGen_PropertyValueInvalid {
            get {
                return ResourceManager.GetString("APGen_PropertyValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The section &lt;{0}&gt; is defined more than once in the same gen file. 的本地化字符串。
        /// </summary>
        internal static string APGen_RedefinedSection {
            get {
                return ResourceManager.GetString("APGen_RedefinedSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Required attribute &apos;{0}&apos; not found. 的本地化字符串。
        /// </summary>
        internal static string APGen_RequiredAttribute {
            get {
                return ResourceManager.GetString("APGen_RequiredAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot add a Section. A section or section group already exists with the name &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string APGen_SectionAlreadyExists {
            get {
                return ResourceManager.GetString("APGen_SectionAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The section is being initialized twice: &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string APGen_SectionInitTwice {
            get {
                return ResourceManager.GetString("APGen_SectionInitTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A section or sectiongroup named &apos;{0}&apos; already exists. 的本地化字符串。
        /// </summary>
        internal static string APGen_SectionNameAlreadyExists {
            get {
                return ResourceManager.GetString("APGen_SectionNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type not found: &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string APGen_TypeNotFound {
            get {
                return ResourceManager.GetString("APGen_TypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unrecognized attribute &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string APGen_UnrecognizedAttribute {
            get {
                return ResourceManager.GetString("APGen_UnrecognizedAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unrecognized attribute &apos;{1}&apos; in &lt;&apos;{0}&apos;&gt;. 的本地化字符串。
        /// </summary>
        internal static string APGen_UnrecognizedAttributeInElement {
            get {
                return ResourceManager.GetString("APGen_UnrecognizedAttributeInElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unrecognized element &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string APGen_UnrecognizedElement {
            get {
                return ResourceManager.GetString("APGen_UnrecognizedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unrecognized configuration section &lt;{0}&gt;. 的本地化字符串。
        /// </summary>
        internal static string APGen_UnrecognizedSection {
            get {
                return ResourceManager.GetString("APGen_UnrecognizedSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Validator does not support type {0}. 的本地化字符串。
        /// </summary>
        internal static string APGen_ValidatorNotSupportType {
            get {
                return ResourceManager.GetString("APGen_ValidatorNotSupportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The pageIndex must be greater than or equal to zero. Index is {0}. 的本地化字符串。
        /// </summary>
        internal static string APPaging_BadIndex {
            get {
                return ResourceManager.GetString("APPaging_BadIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The pageSize must be greater than or equal to zero. PageSize is {0}. 的本地化字符串。
        /// </summary>
        internal static string APPaging_BadPageSize {
            get {
                return ResourceManager.GetString("APPaging_BadPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The combination of pageIndex and pageSize cannot exceed the maximum value of System.Int32. Index is {0} and PageSize is {1}. 的本地化字符串。
        /// </summary>
        internal static string APPaging_BadPageSizeOrIndex {
            get {
                return ResourceManager.GetString("APPaging_BadPageSizeOrIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalidate Email. 的本地化字符串。
        /// </summary>
        internal static string APProject_Regex_Invalidate_Email {
            get {
                return ResourceManager.GetString("APProject_Regex_Invalidate_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalidate URL. 的本地化字符串。
        /// </summary>
        internal static string APProject_Regex_Invalidate_Url {
            get {
                return ResourceManager.GetString("APProject_Regex_Invalidate_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The attribute &apos;connectionStringName&apos; is missing or empty. 的本地化字符串。
        /// </summary>
        internal static string APProvider_ConnectionNameNotSpecified {
            get {
                return ResourceManager.GetString("APProvider_ConnectionNameNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The connection name &apos;{0}&apos; was not found in the applications configuration or the connection string is empty. 的本地化字符串。
        /// </summary>
        internal static string APProvider_ConnectionStringNotFound {
            get {
                return ResourceManager.GetString("APProvider_ConnectionStringNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The provider &apos;{0}&apos; not found. 的本地化字符串。
        /// </summary>
        internal static string APProvider_NotFound {
            get {
                return ResourceManager.GetString("APProvider_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 APSqlJoinType value &apos;{0}&apos; is not supported. 的本地化字符串。
        /// </summary>
        internal static string APQueryParser_APSqlJoinTypeNotSupported {
            get {
                return ResourceManager.GetString("APQueryParser_APSqlJoinTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The filter comparator &apos;Between&apos; must have two values. 的本地化字符串。
        /// </summary>
        internal static string APRptFilter_BetweenMustHaveTwoValues {
            get {
                return ResourceManager.GetString("APRptFilter_BetweenMustHaveTwoValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid datetime. 的本地化字符串。
        /// </summary>
        internal static string APRptFilter_InvalidDateTime {
            get {
                return ResourceManager.GetString("APRptFilter_InvalidDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid number, can not parse to type of &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string APRptFilter_InvalidNumber {
            get {
                return ResourceManager.GetString("APRptFilter_InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid value, can not parse value &apos;{0}&apos; to type of &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string APRptFilter_InvalidValue {
            get {
                return ResourceManager.GetString("APRptFilter_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The filter logic expression invalidate. 的本地化字符串。
        /// </summary>
        internal static string APRptFilter_LogicExpressionInvalidate {
            get {
                return ResourceManager.GetString("APRptFilter_LogicExpressionInvalidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The filter logic expression has Invalidate identifier &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string APRptFilter_LogicIdentifierInvalidate {
            get {
                return ResourceManager.GetString("APRptFilter_LogicIdentifierInvalidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The filter logic expression serial &apos;{0}&apos; not found. 的本地化字符串。
        /// </summary>
        internal static string APRptFilter_LogicSerialNotFound {
            get {
                return ResourceManager.GetString("APRptFilter_LogicSerialNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid string of values. 的本地化字符串。
        /// </summary>
        internal static string APRptFilter_ParseError {
            get {
                return ResourceManager.GetString("APRptFilter_ParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The column type of &apos;{0}&apos; unsupport the filter Comparator &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string APRptFilter_UnsupportComparator {
            get {
                return ResourceManager.GetString("APRptFilter_UnsupportComparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsupport DBNull. 的本地化字符串。
        /// </summary>
        internal static string APRptFilter_UnsupportDBNull {
            get {
                return ResourceManager.GetString("APRptFilter_UnsupportDBNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The filter comparator &apos;{0}&apos; unsupport multi-values. 的本地化字符串。
        /// </summary>
        internal static string APRptFilter_UnsupportMultiValues {
            get {
                return ResourceManager.GetString("APRptFilter_UnsupportMultiValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In datetime column, the comparator &apos;{0}&apos; unsupport special date value, or only one. 的本地化字符串。
        /// </summary>
        internal static string APRptFilter_UnsupportSpecialDateValueOrOnlyOne {
            get {
                return ResourceManager.GetString("APRptFilter_UnsupportSpecialDateValueOrOnlyOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The filter values count can not be zero. 的本地化字符串。
        /// </summary>
        internal static string APRptFilter_ValuesCountCannotBeZero {
            get {
                return ResourceManager.GetString("APRptFilter_ValuesCountCannotBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name cannot contain period. 的本地化字符串。
        /// </summary>
        internal static string APValidate_NameContainPeriod {
            get {
                return ResourceManager.GetString("APValidate_NameContainPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name cannot be empty. 的本地化字符串。
        /// </summary>
        internal static string APValidate_NameEmpty {
            get {
                return ResourceManager.GetString("APValidate_NameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value must not be in the range {0} - {1}. 的本地化字符串。
        /// </summary>
        internal static string APValidate_NumberInTheRange {
            get {
                return ResourceManager.GetString("APValidate_NumberInTheRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value must be in the range {0} - {1}. 的本地化字符串。
        /// </summary>
        internal static string APValidate_NumberOutOfRange {
            get {
                return ResourceManager.GetString("APValidate_NumberOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value must have a resolution of {0}. 的本地化字符串。
        /// </summary>
        internal static string APValidate_NumberResolution {
            get {
                return ResourceManager.GetString("APValidate_NumberResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The string must be at least {0} characters long. 的本地化字符串。
        /// </summary>
        internal static string APValidate_StringAtLeast {
            get {
                return ResourceManager.GetString("APValidate_StringAtLeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The string cannot contain any of the following characters: &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string APValidate_StringInvalidContain {
            get {
                return ResourceManager.GetString("APValidate_StringInvalidContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The string must be no more than {0} characters long. 的本地化字符串。
        /// </summary>
        internal static string APValidate_StringMoreThen {
            get {
                return ResourceManager.GetString("APValidate_StringMoreThen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The TimeSpan value must be positive. 的本地化字符串。
        /// </summary>
        internal static string APValidate_TimeMustBePositive {
            get {
                return ResourceManager.GetString("APValidate_TimeMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The default value for property &apos;{0}&apos; has a different type than the one of the property itself: expected {1} but was {2}. 的本地化字符串。
        /// </summary>
        internal static string APXml_DefaultValueTypeError {
            get {
                return ResourceManager.GetString("APXml_DefaultValueTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The attribute &apos;{0}&apos; may only appear once in this element. 的本地化字符串。
        /// </summary>
        internal static string APXml_DuplicateAttribute {
            get {
                return ResourceManager.GetString("APXml_DuplicateAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The element &lt;{0}&gt; may only appear once in this section. 的本地化字符串。
        /// </summary>
        internal static string APXml_DuplicateElement {
            get {
                return ResourceManager.GetString("APXml_DuplicateElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicate element in collection. 的本地化字符串。
        /// </summary>
        internal static string APXml_DuplicateElementInCollection {
            get {
                return ResourceManager.GetString("APXml_DuplicateElementInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 APXmlElement unsupport IsElementPropery flag in XmlReader or XmlWriter mode. Please use in XmlDocument mode. 的本地化字符串。
        /// </summary>
        internal static string APXml_ElementPropertyUnsupportReaderOrWriter {
            get {
                return ResourceManager.GetString("APXml_ElementPropertyUnsupportReaderOrWriter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collection is not key mode. 的本地化字符串。
        /// </summary>
        internal static string APXml_IsNotKeyModeCollection {
            get {
                return ResourceManager.GetString("APXml_IsNotKeyModeCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property &apos;{0}&apos; is not a APGenElement. 的本地化字符串。
        /// </summary>
        internal static string APXml_NotAElement {
            get {
                return ResourceManager.GetString("APXml_NotAElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value of the property &apos;{0}&apos; cannot be parsed. 的本地化字符串。
        /// </summary>
        internal static string APXml_PropertyCannotBeParsed {
            get {
                return ResourceManager.GetString("APXml_PropertyCannotBeParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property &apos;{0}&apos; not found in gen element. 的本地化字符串。
        /// </summary>
        internal static string APXml_PropertyNotExist {
            get {
                return ResourceManager.GetString("APXml_PropertyNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value for the property &apos;{0}&apos; is not valid. The error is: {1}. 的本地化字符串。
        /// </summary>
        internal static string APXml_PropertyValueInvalid {
            get {
                return ResourceManager.GetString("APXml_PropertyValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Required attribute &apos;{0}&apos; not found. 的本地化字符串。
        /// </summary>
        internal static string APXml_RequiredAttribute {
            get {
                return ResourceManager.GetString("APXml_RequiredAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unrecognized attribute &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string APXml_UnrecognizedAttribute {
            get {
                return ResourceManager.GetString("APXml_UnrecognizedAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unrecognized attribute &apos;{1}&apos; in &lt;&apos;{0}&apos;&gt;. 的本地化字符串。
        /// </summary>
        internal static string APXml_UnrecognizedAttributeInElement {
            get {
                return ResourceManager.GetString("APXml_UnrecognizedAttributeInElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unrecognized element &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string APXml_UnrecognizedElement {
            get {
                return ResourceManager.GetString("APXml_UnrecognizedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Validator does not support type {0}. 的本地化字符串。
        /// </summary>
        internal static string APXml_ValidatorNotSupportType {
            get {
                return ResourceManager.GetString("APXml_ValidatorNotSupportType", resourceCulture);
            }
        }
    }
}
